# Configurações globais da API: Conexão com Banco de Dados MySQL, Migrações Flyway e Propriedades de Segurança JWT.

spring.datasource.url=jdbc:mysql://localhost:3306/barbershop?createDatabaseIfNotExist=true
spring.datasource.username=${DATABASE_USERNAME:seu_usuario}
spring.datasource.password=${DATABASE_PASSWORD:sua_senha}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

server.port=8081

jwt.secret=b4rb3rsh0pb4rb3rsh0pb4rb3rsh0pb4rb3rsh0pb4rb3rsh0p
jwt.expiration=86400000
